In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('DataClassification.csv')

In [2]:
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [3]:
df=df.drop(['Sample code number'],axis=True)
df

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                  5                        1                         1   
1                  5                        4                         4   
2                  3                        1                         1   
3                  6                        8                         8   
4                  4                        1                         1   
..               ...                      ...                       ...   
678                3                        1                         1   
679                2                        1                         1   
680                5                       10                        10   
681                4                        8                         6   
682                4                        8                         8   

     Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
0                    1                            2            1   
1                    5                            7           10   
2                    1                            2            2   
3                    1                            3            4   
4                    3                            2            1   
..                 ...                          ...          ...   
678                  1                            3            2   
679                  1                            2            1   
680                  3                            7            3   
681                  4                            3            4   
682                  5                            4            5   

     Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0                  3                1        1      2  
1                  3                2        1      2  
2                  3                1        1      2  
3                  3                7        1      2  
4                  3                1        1      2  
..               ...              ...      ...    ...  
678                1                1        1      2  
679                1                1        1      2  
680                8               10        2      4  
681               10                6        1      4  
682               10                4        1      4  

[683 rows x 10 columns]

In [4]:
df['Class'].unique()

array([2, 4], dtype=int64)

In [5]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [9]:
from sklearn.linear_model import LogisticRegression
lreg= LogisticRegression(random_state=0)
lreg.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [10]:
y_pred=lreg.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [12]:
confusion_matrix(y_test,y_pred)

array([[103,   4],
       [  5,  59]], dtype=int64)

In [13]:
accuracy_score(y_test,y_pred)

0.9473684210526315

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=10,metric='minkowski',p=2)
knn.fit(X_train,y_train)
knn_ypred=knn.predict(X_test)

In [15]:
confusion_matrix(y_test,knn_ypred)

array([[103,   4],
       [  5,  59]], dtype=int64)

In [16]:
accuracy_score(y_test,y_pred)

0.9473684210526315

In [17]:
from sklearn.svm import SVC
svc=SVC(kernel='linear',random_state=0)
svc.fit(X_train,y_train)
svc_ypred=svc.predict(X_test)


In [18]:
confusion_matrix(y_test,svc_ypred)

array([[102,   5],
       [  5,  59]], dtype=int64)

In [19]:
accuracy_score(y_test,svc_ypred)

0.9415204678362573

In [20]:
from sklearn.svm import SVC
svcn=SVC(kernel='rbf',random_state=0)
svcn.fit(X_train,y_train)
svcn_ypred=svcn.predict(X_test)


In [21]:
confusion_matrix(y_test,svcn_ypred)

array([[101,   6],
       [  3,  61]], dtype=int64)

In [22]:
accuracy_score(y_test,svcn_ypred)

0.9473684210526315

In [23]:
from sklearn.tree import DecisionTreeClassifier
dts=DecisionTreeClassifier(criterion='entropy',random_state=0)
dts.fit(X_train,y_train)
dts_ypred=dts.predict(X_test)

In [24]:
confusion_matrix(y_test,dts_ypred)


array([[104,   3],
       [  4,  60]], dtype=int64)

In [25]:
accuracy_score(y_test,dts_ypred)

0.9590643274853801

In [26]:
from sklearn.ensemble import RandomForestClassifier
rfr=RandomForestClassifier(n_estimators=1000,criterion='entropy',random_state=0)
rfr.fit(X_train,y_train)
rfr_ypred=rfr.predict(X_test)

In [27]:
confusion_matrix(y_test,rfr_ypred)

array([[103,   4],
       [  5,  59]], dtype=int64)

In [28]:
accuracy_score(y_test,rfr_ypred)

0.9473684210526315

In [30]:
print('Accuracy of Logistic Regression-> ',accuracy_score(y_test,y_pred))
print('Accuracy of knn-> ',accuracy_score(y_test,knn_ypred))
print('Accuracy of svc-> ',accuracy_score(y_test,svc_ypred))
print('Accuracy of svcn-> ',accuracy_score(y_test,svcn_ypred))
print('Accuracy of dt-> ',accuracy_score(y_test,dts_ypred))
print('Accuracy of rfr-> ',accuracy_score(y_test,rfr_ypred))

Accuracy of Logistic Regression->  0.9473684210526315
Accuracy of knn->  0.9473684210526315
Accuracy of svc->  0.9415204678362573
Accuracy of svcn->  0.9473684210526315
Accuracy of dt->  0.9590643274853801
Accuracy of rfr->  0.9473684210526315
