In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Data.csv")

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [16]:
df.shape

(10, 4)

In [14]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [24]:
X=df.iloc[:, :-1].values

In [25]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [28]:
Y=df.iloc[:,-1].values

In [29]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [30]:
df1=df

In [32]:
from sklearn.impute import SimpleImputer

In [35]:
imp=SimpleImputer(missing_values=np.nan,strategy='mean')

In [40]:
imp.fit(X[:,1:3])
X[:,1:3]=imp.transform(X[:,1:3])

In [41]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [68]:
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=ct.fit_transform(X)
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [51]:
from sklearn.preprocessing import LabelEncoder

In [53]:
laben=LabelEncoder()
Y=laben.fit_transform(Y)

In [54]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [56]:
from sklearn.model_selection import  train_test_split

In [69]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [70]:
X_train

array([[1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [71]:
X_test

array([[1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [72]:
Y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [73]:
Y_test

array([0, 1])

In [74]:
from sklearn.preprocessing import StandardScaler

In [83]:
stan=StandardScaler()
X_train[:, 3:]=stan.fit_transform(X_train[:, 3:])
X_test[:, 3:]=stan.transform(X_test[:, 3:])


In [84]:
X_train

array([[1.0, 0.0, 0.0, 1.2909944487358058, -0.1915918438457855,
        -1.0781259408412427],
       [1.0, 0.0, 1.0, -0.7745966692414834, -0.014117293757057819,
        -0.07013167641635407],
       [0.0, 1.0, 0.0, -0.7745966692414834, 0.5667085065333239,
        0.6335624327104546],
       [1.0, 0.0, 0.0, 1.2909944487358058, -0.30453019390224867,
        -0.307866172742979],
       [1.0, 0.0, 0.0, 1.2909944487358058, -1.901801144700799,
        -1.4204636155515822],
       [0.0, 1.0, 0.0, -0.7745966692414834, 1.1475343068237056,
        1.2326533634535488],
       [1.0, 0.0, 1.0, -0.7745966692414834, 1.4379472069688966,
        1.5749910381638883],
       [0.0, 1.0, 0.0, -0.7745966692414834, -0.7401495441200352,
        -0.5646194287757336]], dtype=object)

In [85]:
X_test

array([[1.0, 0.0, 1.0, -2.775557561562892e-17, -1.0, -1.0],
       [0.0, 1.0, 0.0, -2.775557561562892e-17, 1.0, 1.0]], dtype=object)