In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
ds=pd.read_csv('diabetes_prediction_dataset.csv')

In [4]:
ds.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [5]:
ds.shape

(100000, 9)

In [6]:
ds.dtypes

gender                  object
age                    float64
hypertension             int64
heart_disease            int64
smoking_history         object
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [7]:
ds.head(5)

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [8]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
ds['gender']=lab.fit_transform(ds['gender'])

In [9]:
ds

gender   age  hypertension  heart_disease smoking_history    bmi  \
0           0  80.0             0              1           never  25.19   
1           0  54.0             0              0         No Info  27.32   
2           1  28.0             0              0           never  27.32   
3           0  36.0             0              0         current  23.45   
4           1  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995       0  80.0             0              0         No Info  27.32   
99996       0   2.0             0              0         No Info  17.37   
99997       1  66.0             0              0          former  27.83   
99998       0  24.0             0              0           never  35.42   
99999       0  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [29]:
ds1=ds.drop(['smoking_history'],axis=True)

In [30]:
ds1

gender   age  hypertension  heart_disease    bmi  HbA1c_level  \
0           0  80.0             0              1  25.19          6.6   
1           0  54.0             0              0  27.32          6.6   
2           1  28.0             0              0  27.32          5.7   
3           0  36.0             0              0  23.45          5.0   
4           1  76.0             1              1  20.14          4.8   
...       ...   ...           ...            ...    ...          ...   
99995       0  80.0             0              0  27.32          6.2   
99996       0   2.0             0              0  17.37          6.5   
99997       1  66.0             0              0  27.83          5.7   
99998       0  24.0             0              0  35.42          4.0   
99999       0  57.0             0              0  22.43          6.6   

       blood_glucose_level  diabetes  
0                      140         0  
1                       80         0  
2                      158         0  
3                      155         0  
4                      155         0  
...                    ...       ...  
99995                   90         0  
99996                  100         0  
99997                  155         0  
99998                  100         0  
99999                   90         0  

[100000 rows x 8 columns]

In [32]:
x=ds1.iloc[:,:-1].values

In [33]:
x

array([[  0.  ,  80.  ,   0.  , ...,  25.19,   6.6 , 140.  ],
       [  0.  ,  54.  ,   0.  , ...,  27.32,   6.6 ,  80.  ],
       [  1.  ,  28.  ,   0.  , ...,  27.32,   5.7 , 158.  ],
       ...,
       [  1.  ,  66.  ,   0.  , ...,  27.83,   5.7 , 155.  ],
       [  0.  ,  24.  ,   0.  , ...,  35.42,   4.  , 100.  ],
       [  0.  ,  57.  ,   0.  , ...,  22.43,   6.6 ,  90.  ]])

In [34]:
y=ds1.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [36]:
x_train

array([[  0.  ,  48.  ,   0.  , ...,  36.26,   4.  , 130.  ],
       [  1.  ,  50.  ,   0.  , ...,  30.68,   5.8 , 155.  ],
       [  0.  ,  63.  ,   0.  , ...,  38.19,   3.5 , 200.  ],
       ...,
       [  1.  ,  80.  ,   1.  , ...,  28.36,   5.8 ,  90.  ],
       [  0.  ,  51.  ,   1.  , ...,  57.51,   6.2 , 126.  ],
       [  0.  ,  79.  ,   0.  , ...,  27.32,   6.  ,  90.  ]])

In [37]:
x_test.shape

(20000, 7)

In [38]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.fit_transform(x_test)

In [39]:
x_train

array([[-8.41523309e-01,  2.69837920e-01, -2.84670433e-01, ...,
         1.34380173e+00, -1.42570544e+00, -1.93790462e-01],
       [ 1.18673244e+00,  3.58562299e-01, -2.84670433e-01, ...,
         5.04431277e-01,  2.54747299e-01,  4.20252620e-01],
       [-8.41523309e-01,  9.35270764e-01, -2.84670433e-01, ...,
         1.63412162e+00, -1.89249787e+00,  1.52553017e+00],
       ...,
       [ 1.18673244e+00,  1.68942799e+00,  3.51283409e+00, ...,
         1.55445711e-01,  2.54747299e-01, -1.17625939e+00],
       [-8.41523309e-01,  4.02924489e-01,  3.51283409e+00, ...,
         4.54032900e+00,  6.28181241e-01, -2.92037355e-01],
       [-8.41523309e-01,  1.64506580e+00, -2.84670433e-01, ...,
        -9.96094308e-04,  4.41464270e-01, -1.17625939e+00]])

In [40]:
from sklearn.neighbors import KNeighborsRegressor
kn=KNeighborsRegressor(n_neighbors=5,metric='minkowski',p=2)
kn.fit(x_train,y_train)

KNeighborsRegressor()

In [68]:
x_train.dtype

dtype('float64')

In [71]:
x_train=x_train.astype('int64')

In [72]:
y_train.dtype

dtype('int64')

In [83]:
kn.predict(ss.transform([[0,80.0,0,1,25.19,6.6,140]]))

array([0.])

In [74]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [75]:
y_pred=kn.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis=1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [76]:
y_pred.shape

(20000,)

In [77]:
y_test.dtype

dtype('int64')

In [78]:
y_pred.dtype

dtype('float64')

In [79]:
y_pred=y_pred.astype('int64')

In [80]:
y_pred.dtype

dtype('int64')

In [81]:
confusion_matrix(y_test, y_pred)

array([[18296,     3],
       [  752,   949]], dtype=int64)

In [82]:
accuracy_score(y_test, y_pred)

0.96225