In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
df=pd.read_csv('heart(1).csv')

In [3]:
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [4]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [5]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [6]:
df['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [7]:
df['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [8]:
df['ExerciseAngina'].unique() 

array(['N', 'Y'], dtype=object)

In [9]:
col_for_label_encoding=['ExerciseAngina','Sex']

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['ExerciseAngina']=le.fit_transform(df['ExerciseAngina'])

In [12]:
df

Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40    1           ATA        140          289          0     Normal   
1     49    0           NAP        160          180          0     Normal   
2     37    1           ATA        130          283          0         ST   
3     48    0           ASY        138          214          0     Normal   
4     54    1           NAP        150          195          0     Normal   
..   ...  ...           ...        ...          ...        ...        ...   
913   45    1            TA        110          264          0     Normal   
914   68    1           ASY        144          193          1     Normal   
915   57    1           ASY        130          131          0     Normal   
916   57    0           ATA        130          236          0        LVH   
917   38    1           NAP        138          175          0     Normal   

     MaxHR  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172               0      0.0       Up             0  
1      156               0      1.0     Flat             1  
2       98               0      0.0       Up             0  
3      108               1      1.5     Flat             1  
4      122               0      0.0       Up             0  
..     ...             ...      ...      ...           ...  
913    132               0      1.2     Flat             1  
914    141               0      3.4     Flat             1  
915    115               1      1.2     Flat             1  
916    174               0      0.0     Flat             1  
917    173               0      0.0       Up             0  

[918 rows x 12 columns]

In [13]:
df=pd.get_dummies(data=df,columns=['ChestPainType','RestingECG','ST_Slope'])

In [14]:
df

Age  Sex  RestingBP  Cholesterol  FastingBS  MaxHR  ExerciseAngina  \
0     40    1        140          289          0    172               0   
1     49    0        160          180          0    156               0   
2     37    1        130          283          0     98               0   
3     48    0        138          214          0    108               1   
4     54    1        150          195          0    122               0   
..   ...  ...        ...          ...        ...    ...             ...   
913   45    1        110          264          0    132               0   
914   68    1        144          193          1    141               0   
915   57    1        130          131          0    115               1   
916   57    0        130          236          0    174               0   
917   38    1        138          175          0    173               0   

     Oldpeak  HeartDisease  ChestPainType_ASY  ChestPainType_ATA  \
0        0.0             0                  0                  1   
1        1.0             1                  0                  0   
2        0.0             0                  0                  1   
3        1.5             1                  1                  0   
4        0.0             0                  0                  0   
..       ...           ...                ...                ...   
913      1.2             1                  0                  0   
914      3.4             1                  1                  0   
915      1.2             1                  1                  0   
916      0.0             1                  0                  1   
917      0.0             0                  0                  0   

     ChestPainType_NAP  ChestPainType_TA  RestingECG_LVH  RestingECG_Normal  \
0                    0                 0               0                  1   
1                    1                 0               0                  1   
2                    0                 0               0                  0   
3                    0                 0               0                  1   
4                    1                 0               0                  1   
..                 ...               ...             ...                ...   
913                  0                 1               0                  1   
914                  0                 0               0                  1   
915                  0                 0               0                  1   
916                  0                 0               1                  0   
917                  1                 0               0                  1   

     RestingECG_ST  ST_Slope_Down  ST_Slope_Flat  ST_Slope_Up  
0                0              0              0            1  
1                0              0              1            0  
2                1              0              0            1  
3                0              0              1            0  
4                0              0              0            1  
..             ...            ...            ...          ...  
913              0              0              1            0  
914              0              0              1            0  
915              0              0              1            0  
916              0              0              1            0  
917              0              0              0            1  

[918 rows x 19 columns]

In [15]:
X=df.drop(['Cholesterol'],axis=True).values
X

array([[ 40.,   1., 140., ...,   0.,   0.,   1.],
       [ 49.,   0., 160., ...,   0.,   1.,   0.],
       [ 37.,   1., 130., ...,   0.,   0.,   1.],
       ...,
       [ 57.,   1., 130., ...,   0.,   1.,   0.],
       [ 57.,   0., 130., ...,   0.,   1.,   0.],
       [ 38.,   1., 138., ...,   0.,   0.,   1.]])

In [16]:
Y=df['Cholesterol'].values
Y

array([289, 180, 283, 214, 195, 339, 237, 208, 207, 284, 211, 164, 204,
       234, 211, 273, 196, 201, 248, 267, 223, 184, 201, 288, 215, 209,
       260, 284, 468, 188, 518, 167, 224, 172, 186, 254, 306, 250, 177,
       227, 230, 294, 264, 259, 175, 318, 223, 216, 340, 289, 233, 205,
       224, 245, 180, 194, 270, 213, 365, 342, 253, 254, 224, 277, 202,
       260, 297, 225, 246, 412, 265, 215, 182, 218, 268, 163, 529, 167,
       100, 206, 277, 238, 223, 196, 213, 139, 263, 216, 291, 229, 208,
       307, 210, 329, 182, 263, 207, 147,  85, 269, 275, 179, 392, 466,
       186, 260, 254, 214, 129, 241, 188, 255, 276, 297, 207, 246, 282,
       338, 160, 156, 248, 272, 240, 393, 230, 246, 161, 163, 230, 228,
       292, 202, 388, 230, 294, 265, 215, 241, 166, 247, 331, 341, 291,
       243, 279, 273, 198, 249, 168, 603, 215, 159, 275, 270, 291, 342,
       190, 185, 290, 195, 264, 212, 263, 196, 225, 272, 231, 238, 222,
       179, 243, 235, 320, 187, 266, 288, 216, 287, 194, 238, 22

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [18]:
X_train.shape

(734, 18)

In [19]:
X_test.shape

(184, 18)

In [20]:
from sklearn.tree import DecisionTreeRegressor

In [21]:
dtr=DecisionTreeRegressor(random_state=0)

In [22]:
dtr.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=0)

In [38]:
dtc_ypred=dtr.predict(X_test)

In [45]:
from sklearn.metrics import r2_score,accuracy_score
r2_score(Y_test,dtc_ypred)


-0.6535121249628852

In [25]:
from sklearn.ensemble import RandomForestRegressor

In [26]:
rfr=RandomForestRegressor(n_estimators=100,random_state=0)
rfr.fit(X_train,Y_train)

RandomForestRegressor(random_state=0)

In [27]:
rfr.predict(X_test)

array([169.02, 149.07, 267.07, 264.43,  53.09, 205.14, 241.92, 228.71,
       243.18, 234.82, 242.17, 215.39, 237.27,  91.11, 208.5 , 205.47,
        90.86, 218.49,  84.06, 196.19,  76.68, 241.62, 230.76, 236.42,
       229.61, 222.22, 239.76, 135.16, 226.16, 246.46, 282.73, 211.47,
       230.13, 230.31, 170.7 ,  21.73, 305.58, 196.87, 256.68, 238.29,
       283.01,  67.03, 230.83, 216.93, 237.02, 217.1 , 148.38, 245.88,
       259.47,  13.56, 163.23, 169.6 , 237.03, 245.88,  21.82, 190.19,
       171.85, 220.15, 234.32, 157.08,  48.81, 273.39, 206.34, 205.42,
       249.66, 170.62, 226.33, 147.54, 260.19, 249.19,  21.13, 223.81,
       103.41, 188.63, 236.47, 107.68, 234.55, 107.47, 221.03, 149.98,
        84.16, 241.43, 251.59, 295.59,  85.8 , 225.44, 272.51, 249.48,
       248.77, 192.89, 270.93, 223.67, 216.76,  39.62, 198.69, 149.06,
       257.3 , 171.21, 188.69, 242.35, 203.89, 211.59, 165.96, 159.96,
       257.58,  91.08, 230.57, 205.56, 112.89, 253.76, 242.97, 238.92,
      

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
reg=LinearRegression()
reg.fit(X_train,Y_train)

LinearRegression()

In [46]:
y_pred=reg.predict(X_test) 

In [47]:
r2_score(Y_test,y_pred)

0.023559958601390485

In [32]:
from sklearn.preprocessing import PolynomialFeatures

In [33]:
poly=PolynomialFeatures(degree=5)
X_poly=poly.fit_transform(X_train)
p_reg=LinearRegression()
p_reg.fit(X_poly,Y_train)

LinearRegression()

In [48]:
poly_ypred=p_reg.predict(poly.fit_transform(X_test))

In [49]:
r2_score(Y_test,poly_ypred)

-5821065.144427209

In [35]:
from sklearn.svm import SVR
sv=SVR(kernel='rbf')
Sreg=LinearRegression()
Sreg.fit(X_train,Y_train)

LinearRegression()

In [50]:
S_ypred=Sreg.predict(X_test)

In [51]:
r2_score(Y_test,S_ypred)

0.023559958601390485