In [1]:
import numpy as np
import pandas as pd


In [7]:
df=pd.read_csv('Folds5x2_pp.csv')

In [9]:
df.shape

(9568, 5)

In [10]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [12]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [16]:
x=df.iloc[:,:-1].values
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [33]:
y=df.iloc[:,-1].values
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [35]:
x_train.shape

(7654, 4)

In [36]:
x_test.shape

(1914, 4)

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
Lreg=LinearRegression()
Lreg.fit(x_train,y_train)

LinearRegression()

In [83]:
y_pred=Lreg.predict(x_test)

In [84]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1))

[[431.23 431.43]
 [460.01 458.56]
 [461.14 462.75]
 ...
 [473.26 469.52]
 [438.   442.42]
 [463.28 461.88]]


In [85]:
#PolynomialRegression
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=5)
x_poly=poly.fit_transform(x_train)
P_reg=LinearRegression()
P_reg.fit(x_poly,y_train)

LinearRegression()

In [48]:
yp_pred=P_reg.predict(poly.fit_transform(x_test))


In [55]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


In [65]:
from sklearn.svm import SVR
svr=SVR(kernel='rbf')
x1=x
y1=y.reshape(len(y),1)


In [66]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler_y=StandardScaler()
y1=scaler_y.fit_transform(y1)
x1=scaler.fit_transform(x1)
x1

array([[-0.63, -0.99,  1.82, -0.01],
       [ 0.74,  0.68,  1.14, -0.97],
       [-1.95, -1.17, -0.19,  1.29],
       ...,
       [ 1.57,  1.58, -0.06, -2.52],
       [ 0.65,  1.19,  0.1 , -0.75],
       [ 0.26,  0.65,  0.67, -0.37]])

In [67]:
y1

array([[ 0.52],
       [-0.59],
       [ 2.  ],
       ...,
       [-1.45],
       [-1.09],
       [-0.06]])

In [68]:
svr.fit(x1,y1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [72]:
svr_ypred=scaler_y.inverse_transform(svr.predict(scaler.transform(x_test)).reshape(-1, 1))

In [74]:
np.set_printoptions(precision=2)
print(np.concatenate((svr_ypred.reshape(len(svr_ypred),1),y_test.reshape(len(y_test),1)),1))

[[433.79 431.23]
 [458.09 460.01]
 [460.49 461.14]
 ...
 [470.76 473.26]
 [439.34 438.  ]
 [461.   463.28]]


In [78]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(random_state=0)
dtr.fit(x_train,y_train)

DecisionTreeRegressor(random_state=0)

In [81]:
dtr_ypred=dtr.predict(x_test)

In [82]:
np.set_printoptions(precision=2)
print(np.concatenate((dtr_ypred.reshape(len(dtr_ypred),1),y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


In [86]:
from sklearn.ensemble import RandomForestRegressor
rdr= RandomForestRegressor(n_estimators=500,random_state=0)
rdr.fit(x_train,y_train)

RandomForestRegressor(n_estimators=500, random_state=0)

In [87]:
rdr_ypred=rdr.predict(x_test)

In [88]:
np.set_printoptions(precision=2)
print(np.concatenate((rdr_ypred.reshape(len(rdr_ypred),1),y_test.reshape(len(y_test),1)),1))

[[433.51 431.23]
 [457.71 460.01]
 [463.53 461.14]
 ...
 [469.21 473.26]
 [439.18 438.  ]
 [461.62 463.28]]


In [92]:
#instances for Linearreg-->> y_pred,y_test
#instances for PolyReg-->> yp_pred,y_test
#instances for SVR-->> svr_ypred,y_test
#instances for dtree-->> dtr_ypred ,y_test
#instances for randfreg-->> rdr_ypred,y_test

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9325315554761303

In [93]:
r2_score(y_test,yp_pred)

0.9447852344480777

In [95]:
r2_score(y_test,dtr_ypred)

0.922905874177941

In [96]:
r2_score(y_test,rdr_ypred)

0.9653381733569701

In [99]:
r2_score(y_test,svr_ypred)

0.9499593513690054